# Generated by Django 4.1.7 on 2023-02-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFP_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='sales', max_length=100),
        ),
    ]
